"""Удаление service_name из APIToken

Revision ID: 09b06985669e
Revises: 4217af283ba4
Create Date: 2025-02-11 12:50:26.052289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09b06985669e'
down_revision: Union[str, None] = '4217af283ba4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_tokens_id'), 'webhook_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_webhook_tokens_token'), 'webhook_tokens', ['token'], unique=True)
    op.drop_column('api_tokens', 'service_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_tokens', sa.Column('service_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_webhook_tokens_token'), table_name='webhook_tokens')
    op.drop_index(op.f('ix_webhook_tokens_id'), table_name='webhook_tokens')
    op.drop_table('webhook_tokens')
    # ### end Alembic commands ###
