"""Add audio_logs

Revision ID: 0f42eba387d9
Revises: 9bf7d18e579d
Create Date: 2025-02-01 17:25:43.881515

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0f42eba387d9'
down_revision: Union[str, None] = '9bf7d18e579d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_login', sa.String(), nullable=True),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('task_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id')
    )
    op.create_index(op.f('ix_audio_logs_id'), 'audio_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audio_logs_user_login'), 'audio_logs', ['user_login'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audio_logs_user_login'), table_name='audio_logs')
    op.drop_index(op.f('ix_audio_logs_id'), table_name='audio_logs')
    op.drop_table('audio_logs')
    # ### end Alembic commands ###
