"""Add table for token2

Revision ID: 9fef1ee25f3a
Revises: 36fbdf897082
Create Date: 2025-02-01 19:06:00.906428

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9fef1ee25f3a'
down_revision: Union[str, None] = '36fbdf897082'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_api_tokens_token', table_name='api_tokens')
    op.drop_table('api_tokens')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_tokens',
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('service_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='api_tokens_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token', 'id', name='api_tokens_pkey')
    )
    op.create_index('ix_api_tokens_token', 'api_tokens', ['token'], unique=True)
    # ### end Alembic commands ###
