"""Add processing_type to AudioLog

Revision ID: c9487ddfd1b6
Revises: f23a56c6872e
Create Date: 2025-02-28 18:16:48.324888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9487ddfd1b6'
down_revision: Union[str, None] = 'f23a56c6872e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audio_logs', sa.Column('processing_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audio_logs', 'processing_type')
    # ### end Alembic commands ###
