"""Добавлено поле has_speech в таблицу audio_logs

Revision ID: f23a56c6872e
Revises: 893a453c1b84
Create Date: 2025-02-19 06:53:12.411375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f23a56c6872e'
down_revision: Union[str, None] = '893a453c1b84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audio_logs', sa.Column('has_speech', sa.Boolean(), nullable=True))
    op.alter_column('audio_logs', 'task_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('audio_logs_task_id_key', 'audio_logs', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('audio_logs_task_id_key', 'audio_logs', ['task_id'])
    op.alter_column('audio_logs', 'task_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('audio_logs', 'has_speech')
    # ### end Alembic commands ###
